# Generated by Django 3.2 on 2021-04-18 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retrocollector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectible',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='retrocollector.type'),
        ),
    ]
